[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "iridium-earth-observation"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "iridium-schemas",
    "pydantic>=2.5.0",
    "httpx>=0.26.0",
]

[tool.setuptools.packages.find]
where = ["."]
packages = ["earth_observation"]
