"""
IRIDIUM shared schemas. Use for API request/response and ingestion contracts.
"""

from iridium_schemas.anomaly import AnomalyEvent
from iridium_schemas.earth_observation import (
    EOAreaPreset,
    EOAreaPresetDefinition,
    EOBandAsset,
    EOIndexLayer,
    EOOverlayDescriptor,
    EOProcessingJob,
    EOScene,
    EOSceneMetadata,
    EOSceneSearchResult,
    EOSourceStatus,
    EOTileLayer,
)
from iridium_schemas.equity import DistrictScore, MobilityEquityScore
from iridium_schemas.events import (
    EnergyGridSignal,
    GNSSPoint,
    IngestionEventBatch,
    PublicEventRecord,
    SensorEvent,
    WeatherSnapshot,
)
from iridium_schemas.forecast import CongestionForecastResponse, ForecastSegment
from iridium_schemas.network import DigitalTwinSnapshot, NetworkEdge, NetworkNode
from iridium_schemas.provenance import (
    DATA_STATUS_CONFIGURATION_REQUIRED,
    DATA_STATUS_LIVE,
    DATA_STATUS_PERMISSION_REQUIRED,
    DATA_STATUS_UNAVAILABLE,
    ProviderRegistryEntry,
    SourceProvenance,
)
from iridium_schemas.routing import (
    RouteAlternative,
    RouteRequest,
    RouteResponse,
    RouteSegment,
)
from iridium_schemas.transit import (
    Alert,
    MetroOperationalNotice,
    MetroRoutingConstraint,
    PredictedArrival,
    RoadTrafficContext,
    RouteRealtimeObservation,
    SegmentCongestionLevel,
    SourceFamily,
    SourceStatus,
    StopRealtimeStatus,
    TransitAgency,
    TransitPartnerRouteResult,
    TransitReadinessReport,
    TransitRoute,
    TransitStop,
    TravelTimeContext,
)

__all__ = [
    "SensorEvent",
    "GNSSPoint",
    "WeatherSnapshot",
    "PublicEventRecord",
    "EnergyGridSignal",
    "IngestionEventBatch",
    "NetworkNode",
    "NetworkEdge",
    "DigitalTwinSnapshot",
    "CongestionForecastResponse",
    "ForecastSegment",
    "RouteRequest",
    "RouteResponse",
    "RouteSegment",
    "RouteAlternative",
    "AnomalyEvent",
    "MobilityEquityScore",
    "DistrictScore",
    "SourceProvenance",
    "ProviderRegistryEntry",
    "DATA_STATUS_LIVE",
    "DATA_STATUS_UNAVAILABLE",
    "DATA_STATUS_CONFIGURATION_REQUIRED",
    "DATA_STATUS_PERMISSION_REQUIRED",
    "TransitAgency",
    "TransitRoute",
    "TransitStop",
    "TransitReadinessReport",
    "SourceFamily",
    "SourceStatus",
    "Alert",
    "PredictedArrival",
    "StopRealtimeStatus",
    "RouteRealtimeObservation",
    "MetroOperationalNotice",
    "MetroRoutingConstraint",
    "RoadTrafficContext",
    "SegmentCongestionLevel",
    "TravelTimeContext",
    "TransitPartnerRouteResult",
    "EOSourceStatus",
    "EOAreaPreset",
    "EOBandAsset",
    "EOSceneMetadata",
    "EOScene",
    "EOSceneSearchResult",
    "EOIndexLayer",
    "EOTileLayer",
    "EOOverlayDescriptor",
    "EOProcessingJob",
    "EOAreaPresetDefinition",
]
